---
- name: uninstalls httpd
  hosts: webservers
  become: true
  tasks:
  - name: stopped httpd
    service:
      name: httpd
      state: stopped

- name: uninstalls apache2
  hosts: dbservers
  become: true
  tasks:
  - name: stopped apache2
    service:
      name: apache2
      state: stopped 
